### ISSUE TITLE
Admin Dashboard is not mapped with the login page. 

### ISSUE THREAD

**Issue by aizakhurram** [aizakhurram/SQE_JTspringBoot_Project#1]
Issue #1
### Errors In admin Login Form:
**Titles**
1. No Proper Error Message is displayed when user/admin enters wrong 'username' or 'password'.
2. Admin Dashboard is not mapped with the login page. (when admin logins, it redirects to the user home page rather than the admin dashboard)

### Reference:
https://www.instagram.com/accounts/login/

### **Severity and Priority**

- Severity Level: 1 (Critical / Blocker / Showstopper)
- Priority Level: 1 (Critical / High Priority / Immediate)

**Steps to reproduce**
1. Run the project
2. Navigate to browser and open the port where the project is running
3. it will open the user login page
4. enter the password and username for admin and it will login but the admin will be redirected to the user home page

**Screenshots of the error**
<img width="1062" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/c59392af-fc67-4fcb-ac5e-7e344c4a7ff0">
admin redirected to user home page upon clicking login button
<img width="1680" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/1f0185f9-159d-4d47-be2a-b2099cb7b5f3">

### Steps to solve the problem:

1. changed the userloginvalidate function in usercontroller.java
added the highlighted code (this will always redirect admin to the adminlogin page and then to the admin dashboard)
<img width="929" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/d4727205-d9e1-4384-a82e-8c1874f90294">

**Comment by usmanf07** [comment]
> Screenshots are a must in reporting bugs. Formally, the following are required in bug reporting format:
> 
> * Title: Provide a concise yet descriptive title for the bug report.
> * Environment: Detail the environment in which the bug occurred. Example system/windows version, the device being used
> * Steps to Reproduce
> * Expected/Actual Behavior
> * Screenshots/Logs/Errors in Console/Exceptions/Error Codes
> * If there is any Additional Information, mention it very briefly and to the point under the heading of "Additional Information"
> * Also assign and prefer to use a numeric based issue ID instead of empty title for example "Issue #1813246: An Error Occured During Login"
> * Also you can provide any other information that might be relevant or helpful in resolving the bug

**Comment by aizakhurram** [comment]
> Screenshots are a must in reporting bugs. Formally, the following are required in bug reporting format:
> 
> * Title: Provide a concise yet descriptive title for the bug report.
> * Environment: Detail the environment in which the bug occurred. Example system/windows version, the device being used
> * Steps to Reproduce
> * Expected/Actual Behavior
> * Screenshots/Logs/Errors in Console/Exceptions/Error Codes
> * If there is any Additional Information, mention it very briefly and to the point under the heading of "Additional Information"
> * Also assign and prefer to use a numeric based issue ID instead of empty title for example "Issue #1813246 An Error Occured During Login"
> * Also you can provide any other information that might be relevant or helpful in resolving the bug

Thank you for highlighting the importance of providing specific details when reporting bug fixes. As beginners, we might not have been fully aware of this practice and we were not provided with these details beforehand, but we sincerely appreciate your guidance. Rest assured, we will keep this in mind for future interactions and strive to improve our communication in reporting.

**Comment by usmanf07** [comment]
First of all, atleast avoid chat gpt in replying to my comments.
Secondly, Your sir has taught you lectures of 1 hour 30 minutes upon these things. You must have atleast knowledge to some extent.
Thirdly, keep on working on the next deliverables because marks will be divided in all the deliverables, you still have chance to score good.
