### ISSUE TITLE
"Add to Cart" Button is not functional on uproduct.jsp

### ISSUE THREAD

**Issue by TayyabNadeem1** [aizakhurram/SQE_JTspringBoot_Project#13]
Issue # 13 (user is not able to add product to cart due to nonfunctional "Add to Cart" button on uproduct page)
Device being used: Hp Elitebook Window 11

**Steps to reproduce the bug**

1. run the project.
2. open the browser and navigate to the port where project is running.
3. login using he username and password of user.
4. click on "Add to Cart" button of any listed products.
5. you will be moved to cartproduct page.
6. click on "Add to Cart" Button which will move you to uprodcut page.
7. There "Add to Cart" button is not functional.

**Screenshots of the error**
<img width="561" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/c4e94d16-7a85-4cad-9ecc-4912df5f1c6e">

**Steps to solve the issue**

1. go to UserController.java file and add the following code
<img width="609" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/626da719-7a9e-40c1-ad39-800ceab1ea5e">
<img width="874" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/066c6de6-531f-4fa3-8992-3491a6ed45b2">
<img width="885" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/06bece80-44fd-4608-a983-61e764d21643">

2. go to uproduct.jsp file and add the following code
<img width="582" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/257e7008-38ae-4e99-9700-517335008d6f">

**Screenshots after resolving issue**
<img width="960" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/72859251-f10f-4c96-a46f-1f20193abfe3">
<img width="960" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/103959510/3f5d821c-f0cb-4969-a17a-556e4d9f31dd">

**Comment by TayyabNadeem1** [comment]
@aizakhurram  please resolve this issue

**Comment by aizakhurram** [comment]
Error resolved:

### Steps to solve the error:
1. go to usercontroller.java, change the /index code and add user object to model and view created (refer to the commits that are relevant to this issue)

**Screenshots after fixing the issue**
<img width="1280" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/d1856207-fc0b-4fe0-84f3-ae06f30febed">

<img width="1665" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/bb06cafc-81f3-4f1b-a2c0-c62b10ee005d">
<img width="1665" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/9ad49af6-c36a-43a1-9fd4-f2ef59097ba6">
