### ISSUE TITLE
A user can register with the same email and username that is already in use.

### ISSUE THREAD

**Issue by TayyabNadeem1** [aizakhurram/SQE_JTspringBoot_Project#2]
Issue # 2
### Errors in User Registration Page
 A user can register with the same email and username that is already in use.

### Reference 
https://instagram.com/accounts/emailsignup/

### **Severity and Priority**

- Severity Level: 2 (Major / High / Severe)
- Priority Level: 1 (Critical / High Priority / Immediate)

**Steps to reproduce the error**
1. Run the project
2. Open browser and navigate to the port where the project is running
3. Click the link "register here" 
4. register the user with the same username as an existing user
5.  the user will be registered

**Expected Behaviour**
The system shall display an error message for invalid username and should not register the user

**Screenshots for the error**
<img width="1066" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/0454261e-5903-4011-9972-5731bb1e15b2">
 
registers user and navigates to login page
<img width="1066" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/8f974f29-7604-4b9b-8517-040da7e57c75">

### Steps to solve the issue
1. Update the UserController.java with the code updated in commit  (change in newuserregister function)
2. Update the register.jsp. add the line ${msg}

<img width="1062" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/c2baf50e-4957-4afb-9079-1378685161dc">
3. go to basedata.sql and add the following constraint  (ALTER TABLE CUSTOMER
ADD UNIQUE (username);)
4.  go to user.java present in models folder and add a line @Column(unique = true) above the line where username is declared
5. go to userdao and add a new function public boolean userExists(String username) and update the userController, userService files accordingly (done in commits)

**Screenshots after solving the issue**
<img width="1062" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/de6b1ff3-68ed-4b8c-8029-fb76fb0b8a67">

**Comment by TayyabNadeem1** [comment]
Good work

**Comment by aizakhurram** [comment]
### Steps to solve the issue
1. Update the UserController.java with the code updated in commit  (change in newuserregister function)
2. Update the register.jsp. add the line ${msg}

<img width="1062" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/c2baf50e-4957-4afb-9079-1378685161dc">
3. go to basedata.sql and add the following constraint  (ALTER TABLE CUSTOMER
ADD UNIQUE (username);)
4.  go to user.java present in models folder and add a line @Column(unique = true) above the line where username is declared
5. go to userdao and add a new function public boolean userExists(String username) and update the userController, userService files accordingly (done in commits)

**Screenshots after solving the issue**
<img width="1076" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/94dd7637-7f31-4825-a0cd-66352ee29cae">

<img width="1062" alt="image" src="https://github.com/aizakhurram/SQE_JTspringBoot_Project/assets/102323528/de6b1ff3-68ed-4b8c-8029-fb76fb0b8a67">
